### ISSUE TITLE
Is the livox GPU node functional

### ISSUE THREAD

**Issue by rachillesf** [ARTI-Robots/gazebo_utils#1]
Hi, thank you for you contribution. I would like to know if the Livox GPU node is functional at this version, I've noticed that it isn't being build in the default CMakeLists.txt.

**Comment by cmuehlbacher** [comment]
Hi
as we have not fully tested the GPU version, we consider it at the moment not fully functional.
It is an initial "port" from the CPU version, but testing is still going on.

**Comment by rachillesf** [comment]
Thank you for your response, closing the issue!
