### ISSUE TITLE
How to use the package of livox simulation?

### ISSUE THREAD

**Issue by EpsAvlc** [ARTI-Robots/gazebo_utils#2]
Excuse me. How to use the package of livox simulation?

**Comment by cmuehlbacher** [comment]
Basically it is just a gazebo plugin thus you can specify it witihn the urdf.

The URDF could look like the following:
[livox_mid.urdf.xacro.txt](https://github.com/ARTI-Robots/gazebo_utils/files/5481934/livox_mid.urdf.xacro.txt)

The corsponding configue would be:
[livox_mid.yaml.txt](https://github.com/ARTI-Robots/gazebo_utils/files/5481935/livox_mid.yaml.txt)


The you can perform the following within the urdf of your robot
[macro_usage.xml.txt](https://github.com/ARTI-Robots/gazebo_utils/files/5481938/macro_usage.xml.txt)

**Comment by EpsAvlc** [comment]
Thank you for your advice. And I did it.
I notice that when I turn on the visualization, there are two parts: Dark blue and light blue. Could you please explain the meaning?
![Uploading Screenshot from 2020-11-04 10-43-54.png…]()

**Comment by EpsAvlc** [comment]
~~And I notice that the pattern for livox lidar is not  non-repetitive. In other words, its static.~~

I have make the scan rotates by changing the rotation_increment to 0.1

**Comment by cmuehlbacher** [comment]
> 
> 
> ~And I notice that the pattern for livox lidar is not non-repetitive. In other words, its static.~
> 
> I have make the scan rotates by changing the rotation_increment to 0.1

The laser rotates accoring the paratmer you changed.
Bassically it is a fixed pattern which is rotated. This is not excatly what the livox does but an approximation. In our experience the sernsor causes more disturbed readings in reality (as most sensors do).

**Comment by cmuehlbacher** [comment]
> Thank you for your advice. And I did it.
> I notice that when I turn on the visualization, there are two parts: Dark blue and light blue. Could you please explain the meaning?
> Uploading Screenshot from 2020-11-04 10-43-54.png…

Can you upload the screen shot again. I can not see the screen shot.
The visualisation itself in gazebo may be missleading as this is done by the standart ray plugin. Thus the pattern may not been properly shown in comparison to the result you seen on the ROS side in RVIZ.

**Comment by EpsAvlc** [comment]
> > Thank you for your advice. And I did it.
> > I notice that when I turn on the visualization, there are two parts: Dark blue and light blue. Could you please explain the meaning?
> > Uploading Screenshot from 2020-11-04 10-43-54.png…
> 
> Can you upload the screen shot again. I can not see the screen shot.
> The visualisation itself in gazebo may be missleading as this is done by the standart ray plugin. Thus the pattern may not been properly shown in comparison to the result you seen on the ROS side in RVIZ.

![Screenshot from 2020-11-04 10-43-54](https://user-images.githubusercontent.com/20700856/98250688-b8ccc780-1fb2-11eb-8350-934521a87f53.png)
The picture is here. Sometimes the two parts are all light blue.

**Comment by cmuehlbacher** [comment]
The visualisation only shows three rays. One left, one in the middle and one right.
The two triangles (left and middle; middle and right) light blue if the outer most ray hits something.
Left you have hit, thus it is more dark then right.

**Comment by EpsAvlc** [comment]
Thank you for your patience. I really appreciate it.
