### ISSUE TITLE
Different fov of livox from official documentation?

### ISSUE THREAD

**Issue by EpsAvlc** [ARTI-Robots/gazebo_utils#3]
From official documentation I learnt that the fov of mid40 is a circle of 38.4 degree.
However, the gazebo plugin seems to have a bigger fov?
Here is the livox plugin's point cloud:
![Screenshot from 2020-11-08 21-31-48](https://user-images.githubusercontent.com/20700856/98466341-ea8b9b80-2209-11eb-997f-b71021b3c568.png)
Here is the actual fov that I drawed in rviz（blue cone):
![Screenshot from 2020-11-08 21-31-59](https://user-images.githubusercontent.com/20700856/98466373-1575ef80-220a-11eb-9d1d-96e41d0f5405.png)

**Comment by EpsAvlc** [comment]
I have measured the fov of the gazebo plugin, and its fov is about 65 degree.

**Comment by cmuehlbacher** [comment]
Hm
Interesting the pattern (an ellipse) is configured to create a cone with 38.4 degrees.
You can check this in arti_gazebo_laser_livox.cpp line 748/749.
You can changes this values to fit the angular but be aware that the pattern should be keept the same as this aproximate the real signal.

**Comment by EpsAvlc** [comment]
It seems that half of the fov is 38.4 degrees ?
![Screenshot from 2020-11-16 14-45-03](https://user-images.githubusercontent.com/20700856/99220997-b839f980-281a-11eb-89a1-560bcf546344.png)

**Comment by EpsAvlc** [comment]
> Hm
> Interesting the pattern (an ellipse) is configured to create a cone with 38.4 degrees.
> You can check this in arti_gazebo_laser_livox.cpp line 748/749.
> You can changes this values to fit the angular but be aware that the pattern should be keept the same as this aproximate the real signal.

And could you explain that how to tune the two parameters?

**Comment by cmuehlbacher** [comment]
> > Hm
> > Interesting the pattern (an ellipse) is configured to create a cone with 38.4 degrees.
> > You can check this in arti_gazebo_laser_livox.cpp line 748/749.
> > You can changes this values to fit the angular but be aware that the pattern should be keept the same as this aproximate the real signal.
> 
> And could you explain that how to tune the two parameters?

The paramters are A and B from the standart representation of an ellipse (https://en.wikipedia.org/wiki/Ellipse#Standard_parametric_representation)
The laser "draws" this ellipse 1 m in front of it. Thus the width and height of the ellipse should be the field of view.
If the FOV is twice the FOV I would suppose reducing both values by half would help as this should reduce keep the ration of the ellipse but should also reduce the longest size.
In generall the ratio between those two values should be keept the same to ensure the pattern stays the same.

**Comment by EpsAvlc** [comment]
Thank you for your time. I have changed the fov of point cloud. The visualization of fov in gazebo, however, doesn't change. How to modify it?

**Comment by EpsAvlc** [comment]
> Thank you for your time. I have changed the fov of point cloud. The visualization of fov in gazebo, however, doesn't change. How to modify it?

Change the angle into half in urdf meet the requirement.

>              <min_angle>0.33</min_angle>
>              <max_angle>-0.33</max_angle>
